---
# Creates a cert8.db file valid for clients, to be installed on client machines
# to recognize https proxy functionalities.

- name: Scarico ca.crt
  get_url:
    url: "http://localhost/proxy.crt"
    dest: /tmp/ca.crt

- name: Creo directory per certificati
  file:
    path: /var/lib/nethserver/ibay/ks/server-ca
    state: directory
    owner: root
    mode: 0755
  sudo: yes

- name: 'Utilizzo cert8.db precedentemente fornito (pulito da FF appena aperto)'
  copy:
    src: cert8.db
    dest: /var/lib/nethserver/ibay/ks/server-ca/cert8.db
    owner: root
    mode: 0644
  sudo: yes

- name: Integro la CA nel db
  shell: certutil -A -n "{{ ansible_local.domain.domainfull }}" -t "TCu,Cuw,Tuw" -i /tmp/ca.crt -d /var/lib/nethserver/ibay/ks/server-ca
  sudo: yes

- name: Pulizia
  shell: rm -f {{ itemÂ }}
  sudo: yes
  with_items:
    - /tmp/ca.crt
    - /var/lib/nethserver/ibay/ks/server-ca/key3.db
    - /var/lib/nethserver/ibay/ks/server-ca/secmod.db
